USE google_ads;

CREATE TABLE ACCOUNTS (
    ID BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(1024) NOT NULL,
    DELETED TINYINT(1),
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME
);

CREATE TABLE CAMPAIGNS (
    ID BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_ID BIGINT(20) NOT NULL,
    NAME VARCHAR(1024) NOT NULL,
    TYPE INT NOT NULL,
    BUDGET BIGINT(20) NOT NULL,
    STATUS INT NOT NULL,
    DELETED TINYINT(1),
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME
);

CREATE TABLE AD_GROUPS (
    ID BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_ID BIGINT(20) NOT NULL,
    CAMPAIGN_ID BIGINT(20) NOT NULL,
    NAME VARCHAR(1024) NOT NULL,
    STATUS INT NOT NULL,
    DELETED TINYINT(1),
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME
);

CREATE TABLE ADS (
    ID BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_ID BIGINT(20) NOT NULL,
    CAMPAIGN_ID BIGINT(20) NOT NULL,
    AD_GROUP_ID BIGINT(20) NOT NULL,
    NAME VARCHAR(1024) NOT NULL,
    TYPE INT NOT NULL,
    STATUS INT NOT NULL,
    FINAL_LINK_URL VARCHAR(1024) NOT NULL,
    DISPLAY_URL VARCHAR(1024) NOT NULL,
    HEAD_LINE VARCHAR(1024) NOT NULL,
    DESCRIPTION VARCHAR(1024) NOT NULL,
    DELETED TINYINT(1),
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME
);

CREATE TABLE LOGIN_SESSION (
    ID BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_ID BIGINT(20) NOT NULL,
    TOKEN VARCHAR(1024) NOT NULL,
    CREATED_AT DATETIME NOT NULL
);

